# Generated by Django 6.0.3 on 2026-03-30 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('book_type', models.CharField(choices=[('give', 'Готов поделиться'), ('want', 'Хочу в свою библиотеку')], max_length=10)),
                ('publisher', models.CharField(blank=True, max_length=128)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('binding', models.CharField(blank=True, choices=[('hard', 'Твердый'), ('soft', 'Мягкий')], max_length=10)),
                ('condition', models.CharField(blank=True, choices=[('perfect', 'Идеальное'), ('normal', 'Нормальное'), ('bad', 'Требует внимания'), ('terrible', 'Годится чтобы подпирать ножку стола')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('archived', 'Архив')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Карточка книги',
                'verbose_name_plural': 'Карточки книг',
            },
        ),
    ]
