# Generated by Django 6.0.3 on 2026-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcard',
            name='book_type',
        ),
        migrations.AddField(
            model_name='bookcard',
            name='action_type',
            field=models.CharField(choices=[('give', 'Готов поделиться'), ('want', 'Хочу в свою библиотеку')], default='want', max_length=10, verbose_name='Выберите пункт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='author',
            field=models.CharField(max_length=128, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='binding',
            field=models.CharField(choices=[('hard', 'Твердый'), ('soft', 'Мягкий')], max_length=10, verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='condition',
            field=models.CharField(choices=[('perfect', 'Идеальное'), ('normal', 'Нормальное'), ('bad', 'Требует внимания'), ('terrible', 'Годится чтобы подпирать ножку стола')], max_length=20, verbose_name='Состояние книги'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='publisher',
            field=models.CharField(blank=True, max_length=128, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('archived', 'Архив')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
