# Generated by Django 6.0.3 on 2026-06-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('auditorium', 'Аудитория'), ('coworking', 'Коворкинг'), ('cinema', 'Кинозал')], max_length=16, verbose_name='Помещение')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала конференции')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], max_length=8, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('planned', 'Мероприятие назначено'), ('completed', 'Мероприятие завершено')], default='new', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Заявка на бронь',
                'verbose_name_plural': 'Заявки на бронь',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Содержимое')),
            ],
        ),
    ]
